spring:
  cloud:
    stream:
      bindings:
        direct:
          binder: rabbit
          destination: p2p-topic
        broadcast:
          binder: rabbit
          destination: pubsub-topic
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin